FROM ffurrer/bats
RUN apk add --no-cache diffutils bash util-linux xxd xmlstarlet 

#COPY --from=BUILD /usr/bin/choose /usr/bin/fd /usr/bin/
#COPY --from=BUILD /usr/bin/fd /usr/bin/fd

ENTRYPOINT [ ]



